---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: imago-updater
  labels:
    app.kubernetes.io/name: imago
    app.kubernetes.io/component: updater

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: imago-updater

subjects:
  - kind: ServiceAccount
    name: imago-updater

...
