---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: imago-updater
  labels:
    app.kubernetes.io/name: imago
    app.kubernetes.io/component: updater

rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "pods"
      - "replicasets"
      - "statefulsets"
    verbs:
      - "list"
  - apiGroups:
      - ""
      - "batch"
    resources:
      - "cronjobs"
    verbs:
      - "get"
      - "list"
      - "update"
  - apiGroups:
      - ""
      - "apps"
    resources:
      - "daemonsets"
      - "deployments"
      - "statefulsets"
      - "replicasets"
    verbs:
      - "get"
      - "list"
      - "update"

...
