---
apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: imago-updater
  labels:
    app.kubernetes.io/name: imago
    app.kubernetes.io/component: updater

spec:
  schedule: "0 4 * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: imago
            app.kubernetes.io/component: updater

        spec:
          serviceAccountName: imago-updater
          restartPolicy: Never

          containers:
            - name: updater
              image: imago-updater
              imagePullPolicy: IfNotPresent

              args:
                - --update

              resources:
                requests:
                  cpu: "0.1"
                  memory: "64M"
                limits:
                  cpu: "1.0"
                  memory: "128M"

...
